substitutions:
  #  Device Info for overrides.
  name: "living-room"
  friendly_name: "Living Room AC"
  room: ""
  
  # Set climate defaults and model
  # https://esphome.io/components/climate/
  # https://esphome.io/components/climate/climate_ir/ - List of supported platforms
  ac_platform: "mitsubishi"
  enable_heat: "false"
  supports_fan_only: "true"

  # WiFi Settings
  wifi_fast_connect: "false"

packages:
  # Download hardware specific template from GitHub - https://esphome.io/components/packages/
  remote_package_files:
    url: https://github.com/mediocreatmybest/esp32
    files: [anthom-rf-ir-remote.yaml]  # optional; if not specified, all files will be included
    ref: main  # optional
    refresh: 1d  # optional

# Defaulting to false to avoid trailing suffix on device names.
esphome:
  name_add_mac_suffix: false

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: "${wifi_fast_connect}"

# Some settings are device specific for configurations. eg. Mitsubishi
climate:
  - platform: ${ac_platform}
    id: !extend primary_ac
    name: "AC"
    set_fan_mode: quiet_4levels
    supports_fan_only: ${supports_fan_only}

api:
  # we can enable api encryption.
  # https://esphome.io/components/api/
  #encryption:
     #key:
  reboot_timeout: 0s
