substitutions:
  #  Device Info for overrides.
  name: "living-room"
  friendly_name: "Living Room AC"
  room: ""
  
  # Set climate defaults and model
  # https://esphome.io/components/climate/
  # https://esphome.io/components/climate/climate_ir/ - List of supported platforms
  ac_platform: "mitsubishi"
  enable_heat: "false"
  
  # Identified Device specific options to be added here.
  set_fan_mode: quiet_4levels
  supports_fan_only: "true"

  # WiFi Settings
  wifi_fast_connect: "false"

packages:
  # Download hardware specific template from GitHub - https://esphome.io/components/packages/
  remote_package_files:
    url: https://github.com/mediocreatmybest/esp32
    files: [athom-rf-ir-remote.yaml]  # optional; if not specified, all files will be included
    ref: main  # optional
    refresh: 1d  # optional

# Defaulting to false to avoid trailing suffix on device names.
esphome:
  name_add_mac_suffix: false

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: "${wifi_fast_connect}"

# Some settings are device specific for configurations. eg. Mitsubishi
climate:
  - id: !extend primary_ac
    name: "AC"
    supports_fan_only: ${supports_fan_only}
    set_fan_mode: ${set_fan_mode}
    # Optional visual block for haos cards.
    visual:
      min_temperature: 15.0
      max_temperature: 30.0
      temperature_step: 1.0

api:
  # we can enable api encryption.
  # https://esphome.io/components/api/
  #encryption:
     #key:
  reboot_timeout: 0s
  # Optional BLE tracker from Athom-rf-ir yaml.
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  # Disable BLE tracking when there are no api connections live
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

esp32_ble_tracker:
  scan_parameters:
    # Don't auto start BLE scanning, we control it in the `api` block's automation.
    continuous: false
    active: true  # send scan-request packets to gather more info, like device name for some devices.
    interval: 320ms  # default 320ms - how long to spend on each advert channel
    window:   300ms  # default 30ms - how long to actually "listen" in each interval. Reduce this if device is unstable.
    # If the device cannot keep up or becomes unstable, reduce the "window" setting. This may be
    # required if your device is controlling other sensors or doing PWM for lights etc.
