# Based on https://github.com/athom-tech/esp32-configs/blob/main/athom-rf-ir-remote.yaml

#=============================================================
# Climate At Home - Hardware Template Athom RF IR Remote
#=============================================================
#
# Package path:
# projects/climate-at-home/packages/hardware/athom-rf-ir-remote.yaml

substitutions:
  # GPIO Definitions
  RF_RX_PIN: GPIO19
  RF_TX_PIN: GPIO18
  IR_RX_PIN: GPIO33
  IR_TX_PIN: GPIO25
  Button_PIN: GPIO0
  LED_PIN: GPIO27
  hardware_description: 'Built on Athom RF IR Remote'
  hardware_status_led: athom_status_led

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  variant: esp32
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: '30'
    # Hardware specific options for latest version of ESPHome that is available for athom-rf-ir-remote device.
    advanced:
      minimum_chip_revision: '3.1'
      sram1_as_iram: true

# Default preference by athom.
preferences:
  flash_write_interval: 1min

#=============================================================
# Hardware Definitions and Sensors
#=============================================================

remote_receiver:
  - pin:
      number: ${IR_RX_PIN}
      inverted: true
      mode:
        input: true
        pullup: true
    # Remove dump all in future after testing.
    # dump: all
    tolerance: 55%
    id: ir_receiver

remote_transmitter:
  - pin:
      number: ${IR_TX_PIN}
      inverted: false
    carrier_duty_percent: 50%
    non_blocking: true
    id: ir_transmitter

binary_sensor:
  - platform: gpio
    pin:
      number: ${Button_PIN}
      mode:
        input: true
      inverted: true
      # Quiet the boot strapping warning here.
      ignore_strapping_warning: true

    name: 'Button'
    id: hardware_button
    internal: true
    on_multi_click:
      - timing:
          - ON for at least 4s
        then:
          - button.press: factory_reset_btn

#=============================================================
# Physical button on device for restart and resets.
#=============================================================
button:
  - platform: restart
    name: 'Restart'
    id: restart_btn
    entity_category: config
    icon: 'mdi:power-cycle'

  - platform: factory_reset
    name: 'Factory Reset'
    id: factory_reset_btn
    entity_category: config
    disabled_by_default: true

  - platform: safe_mode
    name: 'Safe Mode'
    id: safe_mode_btn
    internal: false
    entity_category: config
    disabled_by_default: true

#=============================================================
# Controllable LED, used for internal status.
#=============================================================
output:
  - platform: ledc
    pin: ${LED_PIN}
    id: led_status_output

#========================================================================================
# Switched to monochromatic light platform to allow for effects and brightness control.
#========================================================================================
light:
  - platform: monochromatic
    name: 'Status LED'
    id: athom_status_led
    output: led_status_output
    disabled_by_default: false
    internal: true
    effects:
      - pulse:
          name: 'Dry Down Status'
          transition_length: 1s
          update_interval: 1s
          min_brightness: 10%
          max_brightness: 100%
